{% set version = "4.9.9" %}

package:
  name: tensorflow-datasets
  version: {{ version }}

source:
  url: https://github.com/tensorflow/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0203e65ab136b5e3dcf6a02e0946452b24cae93cb0d7e8b442c3669f12606ffa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  # Skip osx-64 and windows since array_record is not available
  skip: True  # [py<310 or win or (osx and x86_64)]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - absl-py
    - dm-tree
    - etils[edc,enp,epath,epy,etree] >=1.6.0  # [py<311]
    - etils[edc,enp,epath,epy,etree] >=1.9.1  # [py>=311]
    - immutabledict
    - numpy
    - promise
    - protobuf >=3.20
    - psutil
    - pyarrow
    - requests >=2.19.0
    - simple-parsing
    - tensorflow-metadata
    - termcolor
    - toml
    - tqdm
    - wrapt
    # Standard library backports
    - importlib_resources  # [py<39]

test:
  imports:
    - tensorflow_datasets
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.tensorflow.org/datasets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: tensorflow/datasets is a library of datasets ready to use with TensorFlow.
  description: |
    TensorFlow Datasets is a collection of datasets ready to use, with TensorFlow or other Python ML frameworks, such as Jax.
    All datasets are exposed as tf.data.Datasets , enabling easy-to-use and high-performance input pipelines.
  doc_url: https://www.tensorflow.org/datasets
  dev_url: https://github.com/tensorflow/datasets

extra:
  recipe-maintainers:
    - jjhelmus
