{% set version = "4.9.9" %}

package:
  name: tensorflow-datasets
  version: {{ version }}

source:
  url: https://github.com/tensorflow/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0203e65ab136b5e3dcf6a02e0946452b24cae93cb0d7e8b442c3669f12606ffa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: True  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - absl-py
    # Min version of 0.5.0 as old array_record wheel are bugged on all
    # platform except 'x86_64'. See
    # https://github.com/google/array_record/issues/71
    - array_record >=0.5.0  # [linux]
    - dm-tree
    - etils[edc,enp,epath,epy,etree] >=1.6.0  # [python < "3.11"]
    - etils[edc,enp,epath,epy,etree] >=1.9.1  # [python >= "3.11"]
    - immutabledict
    - numpy
    - promise
    - protobuf >=3.20
    - psutil
    - pyarrow
    - requests >=2.19.0
    - simple_parsing
    - tensorflow-metadata
    - termcolor
    - toml
    - tqdm
    - wrapt
    # Standard library backports
    - importlib_resources  # [py<39]

test:
  imports:
    - tensorflow_datasets

about:
  home: http://github.com/tensorflow/datasets
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "tensorflow/datasets is a library of datasets ready to use with TensorFlow."

extra:
  recipe-maintainers:
    - jjhelmus
