{% set version = "4.9.9" %}

package:
  name: tensorflow-datasets
  version: {{ version }}

source:
  url: https://github.com/tensorflow/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0203e65ab136b5e3dcf6a02e0946452b24cae93cb0d7e8b442c3669f12606ffa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: True  # [py<310]

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - absl-py
    - attrs
    - dill
    - future
    - numpy
    - promise
    - protobuf >=3.6.1
    - psutil
    - requests >=2.19.0
    - six
    - tensorflow >=1.14
    - tensorflow-metadata
    - termcolor
    - tqdm
    - wrapt
    - bz2file       # [py27]
    - functools32   # [py27]
    - futures       # [py27]
    - enum34        # [py<34]

test:
  imports:
    - tensorflow_datasets

about:
  home: http://github.com/tensorflow/datasets
  license: Apache Software
  license_family: APACHE
  license_file: LICENSE
  summary: "tensorflow/datasets is a library of datasets ready to use with TensorFlow."

extra:
  recipe-maintainers:
    - jjhelmus
