{% set version = "4.9.9" %}

package:
  name: tensorflow-datasets
  version: {{ version }}

source:
  url: https://github.com/tensorflow/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0203e65ab136b5e3dcf6a02e0946452b24cae93cb0d7e8b442c3669f12606ffa
  patches:  # [linux]
    - patches/0001-Remove-array_record-dependency-from-setup.py.patch  # [linux]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: True  # [py<310]

requirements:
  build:
    - patch  # [linux]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - absl-py
    # array_record dependency commented out - upstream array-record is a mess.
    # No source on PyPI and supply chain concerns with their GitHub repository.
    # - array_record >=0.5.0  # [linux]
    - dm-tree
    - etils[edc,enp,epath,epy,etree] >=1.6.0  # [py<311]
    - etils[edc,enp,epath,epy,etree] >=1.9.1  # [py>=311]
    - immutabledict
    - numpy
    - promise
    - protobuf >=3.20
    - psutil
    - pyarrow
    - requests >=2.19.0
    - simple-parsing
    - tensorflow-metadata >=1.15.0,<1.16.0
    - termcolor
    - toml
    - tqdm
    - wrapt
    # Standard library backports
    - importlib_resources

test:
  source_files:
    - tensorflow_datasets/
  imports:
    - tensorflow_datasets
  requires:
    - pip
    - pytest >=6.0
    - pytest-xdist
    - numpy
    - tensorflow >=2.16  # [py>=310 and py<313]
    - absl-py
    - requests
    - tqdm
    - six
    - packaging
    - importlib_resources
  commands:
    - pip check

    # Python 3.10-3.12: Core tests WITH TensorFlow (avoiding optional dependencies)
    - pytest tensorflow_datasets/core/utils/file_utils_test.py -v  # [py>=310 and py<313]
    - pytest tensorflow_datasets/core/dataset_info_test.py -v  # [py>=310 and py<313]

    # Python 3.13+: Core tests WITHOUT TensorFlow (limited by missing optional dependencies)
    - python -c "from tensorflow_datasets.core.utils import file_utils; print('Core utils import successful')"  # [py>=313]
    - python -c "from tensorflow_datasets.core import dataset_info; print('Dataset info import successful')"  # [py>=313]
    # Run file_utils tests, skipping those that require TensorFlow's mock_fs fixture (not available on Python 3.13)
    - pytest tensorflow_datasets/core/utils/file_utils_test.py -v -k "not (list_dataset_variants or list_datasets_in_data_dir or find_files_without_glob or publish_data)"  # [py>=313]

about:
  home: https://www.tensorflow.org/datasets
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: tensorflow/datasets is a library of datasets ready to use with TensorFlow.
  description: |
    TensorFlow Datasets is a collection of datasets ready to use, with TensorFlow or other Python ML frameworks, such as Jax.
    All datasets are exposed as tf.data.Datasets , enabling easy-to-use and high-performance input pipelines.
  doc_url: https://www.tensorflow.org/datasets
  dev_url: https://github.com/tensorflow/datasets

extra:
  recipe-maintainers:
    - jjhelmus
